platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.9-bullseye

inputs:
- name: external-secrets-repo

outputs:
- name: external-secrets-repo

run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    cd external-secrets-repo
    go install github.com/mikefarah/yq/v4@latest
    make build