platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.9-bullseye

inputs:
- name: external-secrets-repo-gomod

outputs:
- name: external-secrets-repo-gomod

run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail

    # cd external-secrets-repo-gomod
    # # go mod tidy
    # # go install github.com/mikefarah/yq/v4@latest
    
    # Using recommended install method for golangci-lint
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin 
    golangci-lint --version
    