platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

params:
  GOOGLE_CREDENTIALS: ((gcp_concourse_iam))
  GOOGLE_APPLICATION_CREDENTIALS: creds.json

  AWS_ACCESS_KEY_ID: ((aws-access-key-id))
  AWS_ACCESS_KEY_ID_FILE: access-key-id-file

  AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
  AWS_SECRET_ACCESS_KEY_FILE: secret-access-key-file

inputs:
- name: eso-infra-repo

run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    export USE_GKE_GCLOUD_AUTH_PLUGIN=True

    echo "${GOOGLE_CREDENTIALS}" > ${GOOGLE_APPLICATION_CREDENTIALS}
      gcloud auth activate-service-account \
        --key-file "${GOOGLE_APPLICATION_CREDENTIALS}" \
        --project 'kubernetes-cluster-eso'

    echo -n "${AWS_ACCESS_KEY_ID}" > ${AWS_ACCESS_KEY_ID_FILE}
    echo -n "${AWS_SECRET_ACCESS_KEY}" > ${AWS_SECRET_ACCESS_KEY_FILE}

    gcloud container clusters get-credentials kubernetes-cluster-eso \
          --zone=europe-west2-a --project=kubernetes-cluster-eso

    gcloud secrets delete foo-bar --project 'kubernetes-cluster-eso' --quiet || echo "No secret found"
    echo "kubectl context: $(kubectl config current-context)"
    
    echo -e "\n>> Cleaning up cluster resources (force new updates)"
    kubectl delete -f eso-infra-repo/ci/tests || echo "No manifests found"

    echo -e "\n>> Creating gcp authenticaton token for cluster"
    kubectl create secret generic gcpsm-secret --from-file=secret-access-credentials=${GOOGLE_APPLICATION_CREDENTIALS}

    echo -e "\n>> Creating the AWS Credentials to be used by the cluster"
    kubectl create secret generic awssm-secret --from-file=access-key=${AWS_ACCESS_KEY_ID_FILE} --from-file=secret-access-key=${AWS_SECRET_ACCESS_KEY_FILE}

    echo -e "\n>> Removing credentials"
    rm ${GOOGLE_APPLICATION_CREDENTIALS}
    rm ${AWS_ACCESS_KEY_ID_FILE}
    rm ${AWS_SECRET_ACCESS_KEY_FILE}

    echo -e "\n>> Applying ESO manifests"
    kubectl apply -f eso-infra-repo/ci/tests/gcp/gcp-secret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/gcp/gcp-secretstore.yaml
    kubectl apply -f eso-infra-repo/ci/tests/gcp/gcp-pushsecret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/gcp/gcp-external-secret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/vault/vault-secret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/vault/vault-secretstore.yaml
    kubectl apply -f eso-infra-repo/ci/tests/vault/vault-pushsecret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/vault/vault-external-secret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/aws/secrets-manager/aws-secret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/aws/secrets-manager/aws-secretstore.yaml
    kubectl apply -f eso-infra-repo/ci/tests/aws/secrets-manager/aws-pushsecret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/aws/secrets-manager/aws-external-secret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/aws/parameter-store/aws-parameterstore.yaml
    kubectl apply -f eso-infra-repo/ci/tests/aws/parameter-store/aws-pushparameter.yaml
    kubectl apply -f eso-infra-repo/ci/tests/aws/parameter-store/aws-ps-secret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/aws/parameter-store/aws-external-parameter.yaml
