platform: linux

image_resource:
  type: docker-image
  source: {repository: golangci/golangci-lint}

inputs:
- name: external-secrets-repo

run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    cd external-secret-repo
    golangci-lint run
