platform: linux

image_resource:
  type: docker-image
  source:
    repository: europe-west2-docker.pkg.dev/kubernetes-cluster-eso/beach-team-eso/eso-ops-image
    username: _json_key
    password: ((gcp_concourse_iam))

inputs:
- name: external-secrets-trunk

run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    cd external-secrets-trunk
    setup-envtest use -p path 1.20.2
    source <(setup-envtest use 1.20.2 -p env --os $(go env GOOS) --arch $(go env GOARCH))
    go test -v $(go list ./... | grep -v e2e)
