platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.9-bullseye

inputs:
- name: external-secrets-trunk

run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    cd external-secrets-trunk
    go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
    go install github.com/mikefarah/yq/v4@latest
    setup-envtest use -p path 1.20.2
    source <(setup-envtest use 1.20.2 -p env --os $(go env GOOS) --arch $(go env GOARCH))
    go test -v $(go list ./... | grep -v e2e)
