platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

params:    
  GOOGLE_CREDENTIALS: ((gcp_concourse_iam))

inputs:
- name: eso-infra-repo

run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    gcloud container clusters get-credentials kubernetes-cluster-eso \
           --zone=europe-west2-a --project=kubernetes-cluster-eso

    YAML_TEST_FILE=$(ls eso-infrastructure/ci/tests/*.yaml);
    for TEST in $YAML_TEST_FILE; do
       echo "Applying kubectl for $TEST"
       kubectl apply -f eso-infra-repo/ci/tests/*
    done

