platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

params:    
  GOOGLE_CREDENTIALS: ((gcp_concourse_iam))
  GOOGLE_APPLICATION_CREDENTIALS: creds.json

inputs:
- name: eso-infra-repo

run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail

    echo "${GOOGLE_CREDENTIALS}" > creds.json
      gcloud auth activate-service-account \
        --key-file "$GOOGLE_APPLICATION_CREDENTIALS" \
        --project 'kubernetes-cluster-eso'

    gcloud container clusters get-credentials kubernetes-cluster-eso \
           --zone=europe-west2-a --project=kubernetes-cluster-eso
    rm creds.json

    echo "kubectl context: $(kubectl config current-context)"

    YAML_TEST_FILE=$(ls eso-infra-repo/ci/tests/*.yaml);
    for TEST in $YAML_TEST_FILE; do
       echo "Applying kubectl for $TEST"
       kubectl apply -f eso-infra-repo/ci/tests/*
    done

