platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

params:    
  GOOGLE_CREDENTIALS: ((gcp_concourse_iam))
  GOOGLE_APPLICATION_CREDENTIALS: creds.json

inputs:
- name: eso-infra-repo

run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    export USE_GKE_GCLOUD_AUTH_PLUGIN=True

    echo "${GOOGLE_CREDENTIALS}" > ${GOOGLE_APPLICATION_CREDENTIALS}
      gcloud auth activate-service-account \
        --key-file "${GOOGLE_APPLICATION_CREDENTIALS}" \
        --project 'kubernetes-cluster-eso'

    gcloud container clusters get-credentials kubernetes-cluster-eso \
           --zone=europe-west2-a --project=kubernetes-cluster-eso
    rm ${GOOGLE_APPLICATION_CREDENTIALS}
    echo "kubectl context: $(kubectl config current-context)"
    
    echo -e "\n>> TEST[1/5] applying manifest"
    echo "Cleaning up cluster resources (force new updates)"
    kubectl delete -f eso-infra-repo/ci/tests
    # Changing apply to respect an order
    kubectl apply -f eso-infra-repo/ci/secret-example.yaml
    kubectl apply -f eso-infra-repo/ci/secretstore-example.yaml
    kubectl apply -f eso-infra-repo/ci/secretsink-example.yaml
    kubectl apply -f eso-infra-repo/ci/external-secret-example.yaml

    echo -e "\n>> TEST[2/5] SecretStore Validating CAPABILITES:ReadOnly"
    set -x
    kubectl get secretstore secretstore-example |grep ReadOnly
    set +x
    
    echo -e "\n>> TEST[3/5] SecretSink Validating STATUS:SecretSynced"
    set -x
    kubectl get secretsink secretsink-example |grep SecretSynced
    set +x

    echo -e "\n>> TEST[4/5] ExternalSecret Validating STATUS:SecretSynced"
    set -x
    kubectl get externalsecret external-secret-example |grep SecretSynced
    set +x

    echo -e "\n>> TEST[5/5] New Secret has the same value as original Secret"
    set -x
    kubectl get secret external-secret-example -o yaml | grep c2VjcmV0
    set +x
