platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

params:
  GOOGLE_CREDENTIALS: ((gcp_concourse_iam))
  GOOGLE_APPLICATION_CREDENTIALS: creds.json

inputs:
- name: eso-infra-repo

run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    export USE_GKE_GCLOUD_AUTH_PLUGIN=True

    echo "${GOOGLE_CREDENTIALS}" > ${GOOGLE_APPLICATION_CREDENTIALS}
      gcloud auth activate-service-account \
        --key-file "${GOOGLE_APPLICATION_CREDENTIALS}" \
        --project 'kubernetes-cluster-eso'

    gcloud container clusters get-credentials kubernetes-cluster-eso \
           --zone=europe-west2-a --project=kubernetes-cluster-eso
    rm ${GOOGLE_APPLICATION_CREDENTIALS}
    gcloud secrets delete foo-bar --project 'kubernetes-cluster-eso' --quiet || echo "No secrets found"
    echo "kubectl context: $(kubectl config current-context)"

    echo -e "\n>> TEST[1/10] applying manifest"
    echo "Cleaning up cluster resources (force new updates)"
    kubectl delete -f eso-infra-repo/ci/tests || echo "No manifests found"
    # Changing apply to respect an order
    kubectl apply -f eso-infra-repo/ci/tests/gcp/gcp-secret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/gcp/gcp-secretstore.yaml
    kubectl apply -f eso-infra-repo/ci/tests/gcp/gcp-pushsecret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/gcp/gcp-external-secret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/vault/vault-secret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/vault/vault-secretstore.yaml
    kubectl apply -f eso-infra-repo/ci/tests/vault/vault-pushsecret.yaml
    kubectl apply -f eso-infra-repo/ci/tests/vault/vault-external-secret.yaml

    echo -e "\n>> TEST[2/10] GCP SecretStore Validating CAPABILITES:ReadWrite"
    set -x
    kubectl get secretstore gcp-secretstore | grep ReadWrite
    set +x

    echo -e "Sleeping for 5 to ensure resource creation."
    sleep 5
    
    echo -e "\n>> TEST[3/10] GCP PushSecret Validating STATUS:Synced"
    set -x
    kubectl get pushsecret gcp-pushsecret | grep Synced
    set +x

    echo -e "\n>> TEST[4/10] GCP ExternalSecret Validating STATUS:SecretSynced"
    set -x
    kubectl get externalsecret gcp-external-secret | grep SecretSynced
    set +x

    echo -e "\n>> TEST[5/10] New GCP Secret has the same value as original Secret"
    set -x
    kubectl get secret gcp-external-secret -o yaml | grep c2VjcmV0
    set +x

    echo -e "\n>> TEST[6/10] Kubectl describe shows events" # Does this belong in e2e tests?
    set -x
    kubectl describe pushsecret | grep pushsecret
    set +x

    echo -e "\n>> TEST[7/10] Vault SecretStore Validating CAPABILITES:ReadWrite"
    set -x
    kubectl get secretstore vault-secretstore | grep ReadWrite
    set +x

    echo -e "\n>> TEST[8/10] Vault PushSecret Validating STATUS:Synced"
    set -x
    kubectl get pushsecret vault-pushsecret | grep Synced
    set +x

     echo -e "\n>> TEST[9/10] Vault ExternalSecret Validating STATUS:SecretSynced"
    set -x
    kubectl get externalsecret vault-external-secret | grep SecretSynced
    set +x

    echo -e "\n>> TEST[10/10] New Vault Secret has the same value as original Secret"
    set -x
    kubectl get secret vault-external-secret -o yaml | grep world
    set +x
