#!/bin/bash
# set -euo pipefail
export PATH=$PATH:~/go/bin

# echo "RUN: gvm use 1.17"
gvm use 1.17

go install github.com/onsi/ginkgo/v2/ginkgo@latest 

go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest

# list available versions
setup-envtest list --os $(go env GOOS) --arch $(go env GOARCH)

# To use a specific version
setup-envtest use -p path 1.20.2

#To set environment variables
source <(setup-envtest use 1.20.2 -p env --os $(go env GOOS) --arch $(go env GOARCH))

export ETCD_UNSUPPORTED_ARCH=arm64

cd /tmp/lima/external-secrets
echo