---
terraform-common: &terraform-common
  backend_type: gcs
  env_name: development
  env:
    GOOGLE_CREDENTIALS: ((gcp_concourse_iam))
  vars:
    region: europe-west2
    zone: europe-west2-a
    project: kubernetes-cluster-eso

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
- name: eso-infra-repo
  type: git
  icon: github
  check_every: 15m
  source:
    uri: https://github.com/EngineerBetter/eso-infrastructure.git
    branch: master

- name: external-secrets-repo
  type: git
  icon: github
  check_every: 15m
  source:
    uri: https://github.com/external-secrets/external-secrets
    #TODO: parametrize to be utilised by multiple ESO teams
    branch: beach-team 

- name: external-secrets-repo-gosum
  type: git
  icon: github
  check_every: 15m
  source:
    uri: https://github.com/external-secrets/external-secrets
    branch: main
    paths: [go.sum]

- name: terraform-project
  type: terraform
  icon: terraform
  source:
    <<: *terraform-common
    backend_config:
      bucket: terraform-state-eso
      prefix: terraform/state/project

- name: terraform-gke
  type: terraform
  icon: terraform
  source: 
    <<: *terraform-common
    backend_config:
      bucket: terraform-state-eso
      prefix: terraform/state

- name: morning-trigger
  type: time
  icon: clock-outline
  source:
    start: 9:00 AM
    stop: 6:55 PM
    location: Europe/London
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]

- name: evening-trigger
  type: time
  icon: clock-outline
  source:
    start: 7:00 PM
    stop: 7:55 AM
    location: Europe/London
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]

- name: terraform-eso
  type: terraform
  icon: terraform
  source:
    backend_type: gcs
    env_name: development
    env:
      GOOGLE_CREDENTIALS: ((gcp_concourse_iam))
    vars:
      region: europe-west2
      zone: europe-west2-a
      project: kubernetes-cluster-eso
    backend_config:
      bucket: terraform-state-eso
      prefix: terraform/state/eso


- name: eso-golang-image
  type: docker-image
  source:
    repository: europe-west2-docker.pkg.dev/kubernetes-cluster-eso/beach-team-eso/eso-golang-image
    username: _json_key
    password: ((gcp_concourse_iam))

- name: eso-binary-image
  type: docker-image
  source:
    repository: europe-west2-docker.pkg.dev/kubernetes-cluster-eso/beach-team-eso/eso-image
    username: _json_key
    password: ((gcp_concourse_iam))

- name: eso-docker-tag
  type: semver
  source:
    driver: gcs
    key: tags/eso-binary-image
    bucket: terraform-state-eso
    json_key: ((gcp_concourse_iam))

#----------------------------- setup ---------------------------------------------------

groups:
- name: test-build-deploy
  jobs:
  - lint
  - unit-tests
  - build
  - deploy
- name: cluster-management
  jobs:
  - spin-gke-cluster
  - destroy-gke-cluster
- name: setup
  jobs:
  - set-pipeline
  - setup-project

- name: golang-image
  jobs:
  - create-eso-golang-image

jobs:
- name: set-pipeline
  plan:
  - get: external-secrets-repo-gosum
  - get: eso-infra-repo
    trigger: true
  - set_pipeline: self
    file: eso-infra-repo/ci/eso-cd-pipeline.yml

- name: setup-project
  plan:
  - get: eso-infra-repo
    trigger: true
    passed: [set-pipeline]
  - put: terraform-project
    params:
      terraform_source: eso-infra-repo/terraform/project

#----------------------------- cluster management ---------------------------------------

- name: spin-gke-cluster
  plan:
  - get: eso-infra-repo
    passed: [set-pipeline]
  - get: morning-trigger
    trigger: true
  - put: terraform-gke
    params:
      terraform_source: eso-infra-repo/terraform/gke

- name: destroy-gke-cluster
  plan:
  - get: eso-infra-repo
    passed: [set-pipeline]
  - get: evening-trigger
    trigger: true
  - put: terraform-gke
    params:
      terraform_source: eso-infra-repo/terraform/gke
      action: destroy
    get_params:
      action: destroy

# --------------------------------- build go deps image ---------------------------------
- name: create-eso-golang-image
  serial: true
  plan:
  - get: external-secrets-repo-gosum
    passed: [set-pipeline]
    trigger: true
  - get: eso-infra-repo
  - task: go-build
    file: eso-infra-repo/ci/tasks/create-eso-golang-image.yml
  - put: eso-golang-image
    params:
      build: external-secrets-repo-gosum
      build_args:
        TARGETOS: linux
        TARGETARCH: amd64
# TODO: tag with external-secrets-repo sha
#     tag_file: eso-docker-tag/version
      tag_as_latest: true
    get_params: {skip_download: true}


#---------------------------------- code part -------------------------------------------

- name: lint
  plan:
  - get: external-secrets-repo
    trigger: true
  - get: eso-infra-repo
    passed: [set-pipeline]
  - task: lint-files
    file: eso-infra-repo/ci/tasks/golint.yml

- name: unit-tests
  plan:
  - get: external-secrets-repo
    trigger: true
    passed: [lint]
  - get: eso-infra-repo
    passed: [lint]
  - task: run-unit-tests
    file: eso-infra-repo/ci/tasks/gotest.yml

- name: build
  serial: true
  plan:
  - get: eso-infra-repo
    passed: [unit-tests]
  - get: external-secrets-repo
    trigger: true
    passed: [unit-tests]
  - get: eso-docker-tag
    params: {bump: minor}
  - task: go-build
    file: eso-infra-repo/ci/tasks/build-binary.yml
  - put: eso-binary-image
    params:
      build: external-secrets-repo
      build_args:
        TARGETOS: linux
        TARGETARCH: amd64
      tag_file: eso-docker-tag/version
      tag_as_latest: true
    get_params: {skip_download: true}
  - put: eso-docker-tag
    params: {file: eso-docker-tag/version}

- name: deploy
  plan:
  - get: eso-docker-tag
    passed: [build]
  - get: eso-infra-repo
    passed: [build]
  - get: external-secrets-repo
    trigger: true
    passed: [build]
  - task: generate-crds
    file: eso-infra-repo/ci/tasks/generate-crds.yml
  - put: terraform-eso
    params:
      terraform_source: eso-infra-repo/terraform/eso
      vars:
        helm_charts_dir: ../../../external-secrets-repo/deploy/charts/external-secrets
        image_registry: europe-west2-docker.pkg.dev/kubernetes-cluster-eso/beach-team-eso/eso-binary-image
        version_file: ../../../eso-docker-tag/version
