---
resources:
- name: eso-infra-repo
  type: git
  icon: github
  check_every: 15m
  source:
    uri: https://github.com/EngineerBetter/eso-infrastructure.git
    branch: master

- name: external-secrets-repo-gomod
  type: git
  icon: github
  check_every: 15m
  source:
    uri: https://github.com/external-secrets/external-secrets
    branch: main
    paths: [go.mod]

- name: eso-ops-image
  type: docker-image
  source:
    repository: europe-west2-docker.pkg.dev/kubernetes-cluster-eso/beach-team-eso/eso-ops-image
    username: _json_key
    password: ((gcp_concourse_iam))

jobs:
- name: set-pipeline
  plan:
  - get: external-secrets-repo-gomod
  - get: eso-infra-repo
    trigger: true
  - set_pipeline: self
    file: eso-infra-repo/ci/eso-ops-pipeline.yml


- name: create-eso-ops-image
  plan:
  - get: external-secrets-repo-gomod
    passed: [set-pipeline]
    trigger: true
  - get: eso-infra-repo
  - task: prep-eso-ops-image
    file: eso-infra-repo/ci/tasks/prep-eso-ops-image.yml
  - put: eso-ops-image
    params:
      build: builddir
      dockerfile: eso-infra-repo/ci/eso-ops/Dockerfile
      docker_buildkit: 1
      tag_file: external-secrets-repo-gomod/.git/ref
      tag_as_latest: true
    get_params: {skip_download: true}
