resources:
- name: external-secrets-repo
  type: git
  icon: github
  check_every: 15m
  source:
    uri: https://github.com/external-secrets/external-secrets
    branch: beach-team

- name: eso-infra-repo
  type: git
  icon: github
  check_every: 15m
  source:
    uri: https://github.com/EngineerBetter/eso-infrastructure.git
    branch: master

- name: eso-image
  type: docker-image
  source:
    repository: europe-west2-docker.pkg.dev/kubernetes-cluster-eso/beach-team-eso/eso-image
    username: _json_key
    password: ((gcp_concourse_iam))

- name: eso-docker-tag
  type: semver
  source:
    driver: gcs
    key: tags/eso-image
    bucket: terraform-state-eso
    json_key: ((gcp_concourse_iam))

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: eso-infra-repo
    trigger: true
  - set_pipeline: self
    file: eso-infra-repo/ci/eso-tests.yaml

- name: lint
  serial: true
  plan:
  - get: external-secrets-repo
    trigger: true
  - get: eso-infra-repo
    trigger: true
    passed: [set-pipeline]
  - task: lint-files
    file: eso-infra-repo/ci/tasks/golint.yaml

- name: test
  serial: true
  plan:
  - get: external-secrets-repo
    trigger: true
  - get: eso-infra-repo
    trigger: true
    passed: [set-pipeline]
  - task: run-unit-tests
    file: eso-infra-repo/ci/tasks/gotest.yaml

- name: build
  serial: true
  plan:
  - get: external-secrets-repo
    trigger: true
    passed: [test, lint]
  - get: eso-docker-tag
    params: {bump: minor}
  - task: go-build
    file: eso-infra-repo/ci/tasks/build-binary.yaml
  - put: eso-image
    params:
      build: external-secrets-repo
      build_args:
        TARGETOS: linux
        TARGETARCH: amd64
      tag_file: eso-docker-tag/version
      tag_as_latest: true
    get_params: {skip_download: true}