terraform-common: &terraform-common
  backend_type: gcs
  env_name: development
  env:
    GOOGLE_CREDENTIALS: ((gcp_concourse_iam))

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
- name: eso-infra-repo
  type: git
  icon: github
  check_every: 15m
  source:
    uri: https://github.com/EngineerBetter/eso-infrastructure.git
    branch: master
    
- name: terraform-gke
  type: terraform
  icon: terraform
  source: 
    <<: *terraform-common
    backend_config:
      bucket: terraform-state-eso
      prefix: terraform/state
    vars:
      region: europe-west2
      zone: europe-west2-a
      project: kubernetes-cluster-eso
      service_account: concourse@kubernetes-cluster-eso.iam.gserviceaccount.com

- name: terraform-eso
  type: terraform
  icon: terraform
  source:
    <<: *terraform-common
    backend_config:
      bucket: terraform-state-eso
      prefix: terraform/state/eso
    vars:
      region: europe-west2
      zone: europe-west2-a
      project: kubernetes-cluster-eso

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: eso-infra-repo
    trigger: true
  - set_pipeline: self
    file: eso-infra-repo/ci/pipeline.yaml

- name: spin-gke-cluster
  plan:
  - get: eso-infra-repo
    trigger: true
    passed: [set-pipeline]
  - put: terraform-gke
    params:
      terraform_source: eso-infra-repo/terraform/gke

- name: install-eso
  plan:
  - get: eso-infra-repo
    trigger: true
    passed: [spin-gke-cluster]
  - put: terraform-eso
    params:
      terraform_source: eso-infra-repo/terraform/eso